name: $(Build.BuildNumber)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
stages:
  - stage: 'Versioning'
    jobs:
    - job: 'GitVersion'
      steps:
      - template: '.pipelines/.templates/generate.version.yml'

  - stage: 'Build'
    jobs:
    - job: 'BuildJob'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'dotnet-conventionalcommit-changelog.sln'

  - stage: 'UnitTests'
    jobs:
    - job: 'RunUnitTests'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: 'dotnet-conventionalcommit-changelog.sln'

  - stage: 'MutationTests'
    jobs:
    - job: 'RunMutationTests'
      steps:
      - task: PowerShell@2
        inputs:
          filePath: '.pipelines/.scripts/run.mutation.tests.ps1'
          arguments: '$(System.DefaultWorkingDirectory)/mutation-tests'
      - template: '.pipelines/.templates/publish.mutation.test.results.yml'
